name = input("enter your name")
branch = input("enter your branch")
gender = input("enter your gender")
college = input("enter your college")
age = input("enter your age")
print("hiii ")
print("your name is : ", name)
print("your branch is : ", branch)
print("your gender is : ", gender)
print("your college name is :", college)
print("your age is : ", age)
